version: '2'
services:
  pttg-generic-ui:
    container_name: income-ui-container
    image: quay.io/ukhomeofficedigital/pttg-ip-gt-ui:v0.1.0-23.84ef12d
    ports:
     - "8000:8080"
    links:
     - pttg-income-proving-api.pt-i-dev.svc.cluster.local
  pttg-income-proving-api.pt-i-dev.svc.cluster.local:
    container_name: income-api-container
    image: quay.io/ukhomeofficedigital/pttg-income-proving-api:0.1.0-87.0d84b86
    ports:
     - "80:8080"
  pttg-mongodb.pt-i-dev.svc.cluster.local:
    container_name: mongo-container
    image: quay.io/ukhomeofficedigital/pttg-test-mongodb:0.1.0
    ports:
    - "27017:27017"
  pttg-test-loader-mongodb:
    container_name: mongo-loader-container
    image: quay.io/ukhomeofficedigital/pttg-test-loader-mongodb:0.1.0





# Prerequisites

# - Linked services - host in linked service URL must match service name defined above eg. http://income:8081
# - Any ports required for docker container coummunication must be exposed in the source application's dockerFile eg:
#      .. ..
#      EXPOSE 8081
#      .. ..
# -. Any port to be published to the host machine eg accessible from localhost should have a port definition
